# Generated by Django 4.2.24 on 2025-11-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easebuzz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='easebuzz_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='easebuzz_salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='jiopay_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='merchant',
            name='jiopay_salt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
