from django.urls import path
from . import views

urlpatterns = [
    path("add-merchant/", views.add_merchant, name="add-merchant"),
    path("list_merchants/", views.list_merchants, name="list_merchants"),
    path("update-merchant/", views.update_merchant, name="update-merchant"),
    path("merchant-stats/", views.merchant_stats, name="merchant-stats"),
    path("merchant/services/", views.merchant_services, name="merchant_services"),
    path("active_sessions/", views.active_sessions, name="active_sessions"),
    path("active_currency/", views.active_currency, name="active_currency"),
    path("all_bulk_sheets/",views.all_bulk_sheets, name="all_bulk_sheets"),

    path("payout_dashboard/", views.payout_dashboard_stats, name="payout_dashboard_stats"),
    path("easebuzz/payout_merchants/", views.payout_merchants_api, name="payout_merchants_api"),
    path("payout/callback_details/", views.get_payout_callback_details, name="payout-callback-details"),
    path("payout/pending_wallet_requests/", views.pending_wallet_requests, name="pending-wallet-requests"),
    path("payout/ticket_status/", views.get_ticket_status, name="payout-ticket-status"),
    path("payout/transaction/", views.payout_transaction, name="payout-transaction"),
    path("payout/request_history/", views.payout_request_history, name="payout-request-history"),
    path("payout/virtual_transaction/", views.payout_virtual_transaction, name="payout-virtual-transaction"),
    path("payout/acquirer_report/", views.payout_acquirer_report, name="payout-acquirer-report"),
    path("payout/add_account/", views.get_add_account, name="payout-add-account"),
    path("payout/activate_account/", views.get_activate_account, name="payout-activate-account"),
    path("payout/bank_statements/", views.get_bank_statements, name="payout-bank-statements"),
    path("payout/bank_balance/", views.get_bank_balance, name="payout-bank-balance"),
    path("payout/bulk_update_transaction/", views.bulk_update_transaction, name="payout-bulk-update"),
    path("payout/sample_file/", views.download_sample_file, name="payout-sample-file"),
    path("payin_dashboard/", views.payin_dashboard, name="payin-dashboard"),
    path("easebuzz/payin_ticket_status/", views.payin_ticket_status, name="payin_ticket_status"),
    path("easebuzz/currency_list/", views.currency_list, name="currency_list"),
    path("easebuzz/update_currency/", views.update_currency, name="update_currency"),
    path("easebuzz/payin_callback_details/", views.payin_callback_details, name="payin_callback_details"),
    path("easebuzz/download_callback_report/", views.download_callback_report, name="download_callback_report"),
    path("easebuzz/payin_request_list/", views.payin_request_list, name="payin_request_list"),
    path("easebuzz/download_payin_report/", views.download_payin_report, name="download_payin_report"),
    path("easebuzz/payin_request_list/", views.payin_request_list),
    path("easebuzz/payin_transaction_history/", views.payin_transaction_history),
    path("easebuzz/payin_chargeback_transactions/", views.payin_chargeback_transactions),
    path("easebuzz/payin_dispute_transactions/", views.payin_dispute_transactions),
    path("easebuzz/payin_flag_transactions/", views.payin_flag_transactions),
    path("easebuzz/payin_virtual_transactions/", views.payin_virtual_transactions),
    path("easebuzz/payin_unmatched_transactions/", views.payin_unmatched_transactions),
    path("easebuzz/payin_acquirer_report/", views.payin_acquirer_report),
    path("easebuzz/fraud_list/", views.fraud_list_api, name="fraud_list_api"),
    path("payin/master/add-mid/", views.payin_master_add_mid_api, name="payin_master_add_mid_api"),
    path("payin/master/activate-mid/", views.payin_master_activate_mid_api, name="payin_master_activate_mid_api"),
    path("product/list/", views.easebuzz_product_list, name="easebuzz_product_list"),
    path("product/query/", views.product_query, name="product_query"),
    path("product/transaction/", views.product_transaction, name="product_transaction"),
]
